### PR TITLE
Improvements and fixes

### PR DESCRIPTION
**Pull request by Candas1**
Change:
- Removed the code for limiting that works only for one loop (feedback from vamfun)
- Alternate ADC wiring parameter, it's available in Transpotter and can be useful later
- Alternate pin mapping parameter, for boards with extra white wire on hall sensor cable (seen by Vamfun and other users)
- Removed use of malloc to fix issue with board freezing if too many commands are send with debug protocol
- Added Battery voltage, Temperature, and currents in debug protocol

### CODE REVIEW

**Comment by Candas1** [comment]
Hi, 
I haven't had time to check the loop delay yet.
Emanuel will probably implement it and I will help to test.
As we need to make sure it works with all variants.

**Comment by EmanuelFeru** [comment]
I am planning to implement it in this PR in the weekend.

**Comment by vamfun** [comment]
I still think you should fix default print statement along with the delay fix.  At least in my experience it takes about 1 ms per 8 characters printed.   So with the current format , you exceed the 5ms frame time whenever you print.  Keeping the characters less than 32 per print maintains a 5ms frame.(code uses about 1ms leaving 4ms to print.
So simply alternating between two 32 character print formats would keep a 5ms frame even with a 10ms print cycle.
I would collect the long term calibration variables like battery and temperature parameters in one statement and the dynamic variables in another statement.     If someone wanted to use a 5ms print rate they could simply comment the slower variables.

**Comment by EmanuelFeru** [comment]
Do you collect the data in Ascii or binary? Because in binary i think is faster.

**Comment by vamfun** [comment]
Not sure... Just using putty with debug main printf similar to what's in the unmodified FOC firmware.  It's jusT uart serial transmission to USB converter to PC.  Are there some settings that permit faster Xmission?  In theory I should be able to see a data rate of 12 char/ms with 115200 baud but I was measuring an effective rate of only 8 char/ms.

**Pull request merged**
