### PR TITLE
Update SideboardLeds and Feedback for each sideboard separately

### PR DESCRIPTION
**Pull request by yashatan**
Update for Hoverboard mode.
SideboardLeds() ----> SideboardLeds_L(); and SideboardLeds_R();.
Feedback -----> Feedback_L and Feedback_R.
The old way make DMA always send the newest.

### CODE REVIEW

**Comment by EmanuelFeru** [comment]
The Platformio build for some variants failed. Can you fix it?

**Comment by yashatan** [comment]
Yeah. It's only for VARIANT_HOVERBOARD.

No. I even not install platformio yet. Maybe later i will find out.

**Comment by yashatan** [comment]
>The Platformio build for some variants failed. Can you fix it?

And I would prefer that only VARIANT_HOVERBOARD has 2 Sideboards LEDs and 2 Feedback structures. The other variants cannot use 2 sideboards anyway, because one cable is always used for control, and the other one can be used for a sideboard (if desired).

I have fixed all of those teacher.

**Comment by EmanuelFeru** [comment]
@yashatan with the latest UART improvements, I already included some of your suggestions from this PR. So, I have to close this PR. Sorry that it came like this.
Feel free to come with new Pull Requests.

**Pull request closed without merging**
