### PR TITLE
improved VARIANT_ADC documentation in config.h

### PR DESCRIPTION
**Pull request by larsmm**
Hi, please add this.

### CODE REVIEW

**Comment by Candas1** [comment]
Hi,

A few things I noticed yesterday when trying the PR:
- is [this](https://github.com/larsmm/hoverboard-firmware-hack-FOC/blob/c57e1a0e4ed4a989f250480ef88aafa4702a5761/Src/main.c#L427) a mistake ?
- such  [messages](https://github.com/larsmm/hoverboard-firmware-hack-FOC/blob/c57e1a0e4ed4a989f250480ef88aafa4702a5761/Src/main.c#L478) are flooding usart as it is shown for each loop
- USART variant didn't work at all, I am not sure why, need to try again
- I was using debug usart but started to send binary frames to the board, the board became unresponsive. It might be happening [here](https://github.com/larsmm/hoverboard-firmware-hack-FOC/blob/c57e1a0e4ed4a989f250480ef88aafa4702a5761/Src/util.c#L1097), the board is getting many commands and replying back, before it wasn't waiting for the buffer to be empty, now it could be that it's overloaded by all the messages to send

I think what Emanuel mentioned is the size of the code also that could prevent Keil users to flash the code.
One idea he mentioned is that with #ifdef DEBUG_SERIAL_USARTX condition this piece could be deactivated if not needed.
I am not sure if use of printf instead of sprintf is increasing the size, but being able to print floats is increasing size significantly and can be managed with other workaround.

**Comment by larsmm** [comment]
1. Yes, that is a mistake. Delete this line.
2. Yes these messages are floating the loop but the protections is working. Running it not on every loop would be better for printing, but then the protection is not as fast. For overheat and battery voltage this is not a problem, maybe for the timeouts and whatever that is: rtY_Left.z_errCode? It depends on how fast these values are beeing resetted.
3. I have no setup for testing this VARIANT_USART.
4. A possible solution would be to set a variable (disable_printf_buffer_wait = 1;) before a no-wait-printf. So we are able to use both methods.

Why should someone use a flash tool with a software code size limitation? There are free and easy to use tools like vscode + platformio without this limitation.

**Comment by EmanuelFeru** [comment]
@larsmm  if I have time this week I will take a look at this PR.

**Comment by Candas1** [comment]
Hi, just a comment. 
I mentioned before that USART Variant wasn't working anymore. 
I found out the issue is when sending the [usart feedback](https://github.com/larsmm/hoverboard-firmware-hack-FOC/blob/18ac2bc2241d13be52d6c5d4acb2c4c3416cf2f0/Src/main.c#L447), but I am not sure how to fix it.

**Comment by EmanuelFeru** [comment]
@Candas1 you mean it is not working in this PR?
Because then I know why is not working. It is due to the fact the configuration for UART is changed in this PR. I will have a look if there is a way to use printf but with main branch UART configuration.

**Comment by Candas1** [comment]
> @Candas1 you mean it is not working in this PR?
> Because then I know why is not working. It is due to the fact the configuration for UART is changed in this PR. I will have a look if there is a way to use printf but with main branch UART configuration.

Yes in this PR

**Comment by EmanuelFeru** [comment]
* printf works now with default UART settings
* some clean-up still to do (maybe indeed we can remove the consoleLog and the buffer itself).
* I am not sure if we really need the printf for errors.. I will see

Below a short comparison (most increase is due to the added text in printf):
```
VARIANT_ADC:

Before
RAM:   [=         ]   6.9% (used 3388 bytes from 49152 bytes)
Flash: [=         ]  10.8% (used 28324 bytes from 262144 bytes)

After
RAM:   [=         ]   5.0% (used 2460 bytes from 49152 bytes)
Flash: [=         ]  11.0% (used 28960 bytes from 262144 bytes)

==> +636 bytes (+0.2%)


VARIANT_HOVERCAR:

Before
RAM:   [=         ]   6.8% (used 3320 bytes from 49152 bytes)
Flash: [=         ]  10.3% (used 26972 bytes from 262144 bytes)

After
RAM:   [=         ]   5.1% (used 2520 bytes from 49152 bytes)
Flash: [=         ]  11.4% (used 29828 bytes from 262144 bytes)

==> +2856 bytes (+1.1%)
```

**Pull request merged**
