### PR TITLE
Some prettifying, typos, renaming

### PR DESCRIPTION
**Pull request by pinguinpfleger**
it is too late for trivial tasks

### CODE REVIEW

**Comment by EmanuelFeru** [comment]
At a quick look there are a lot of warnings:
```
<command-line>:0:0: warning: "PLATFORMIO" redefined
```
Do you know why is that?

**Comment by pinguinpfleger** [comment]
hmm when does it happen?

**Comment by EmanuelFeru** [comment]
The build passes indeed. But if you look in platformio build, there are a lot of warnings. It used to be warning free.

**Comment by pinguinpfleger** [comment]
found it!


COLLECT_GCC_OPTIONS='-o' '.pio/build/VARIANT_ADC/FrameworkCMSISDevice/system_stm32f1xx.o' '-c' '-g' '-ggdb' '-v' '-Os' '-ffunction-sections' '-fdata-sections' '-Wall' '-mthumb' '-mcpu=cortex-m3' '-nostdlib' '-D' 'PLATFORMIO=40100' '-D' 'STM32F103xE' '-D' 'STM32F1' '-D' 'USE_HAL_DRIVER' '-D' 'STM32F103xE' '-D' 'VARIANT_ADC' '-D' 'PLATFORMIO' '-D' 'USE_HAL_DRIVER' '-D' 'F_CPU=72000000L' '-I' 'inc' '-I' '/Users/kaihauser/.platformio/packages/framework-stm32cube/f1/Drivers/CMSIS/Include' '-I' '/Users/kaihauser/.platformio/packages/framework-stm32cube/f1/Drivers/CMSIS/Device/ST/STM32F1xx/Include' '-I' '/Users/kaihauser/.platformio/packages/framework-stm32cube/f1/Drivers/STM32F1xx_HAL_Driver/Inc' '-I' '/Users/kaihauser/.platformio/packages/framework-stm32cube/f1/Drivers/BSP/Components/Common'

I had a typo which you had fixed (PALTFORMIO)
https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/commit/827a490f349ca2c2ad6288adcf89e63b9833ab83 <https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/commit/827a490f349ca2c2ad6288adcf89e63b9833ab83>

the code worked anyway because platformio already set -D' 'PLATFORMIO=40100‘

so if the env var get by anyway we can just delete the extra define.

**Comment by EmanuelFeru** [comment]
good that you found it :) I will  do a final check soon.

**Comment by EmanuelFeru** [comment]
Just for my own curiosity, I see you removed "-D PLATFORMIO" from platformio.ini. Where is now this define located? (because is being used in config.h)  because I cannot find it, but is for sure somewhere.

**Comment by EmanuelFeru** [comment]
Kai, I really like the prettifying in config.h.
It is much much more clean and organized.
Great job! Thanks again!

**Comment by EmanuelFeru** [comment]
I forgot to merge :D

**Pull request merged**
